DS_SKIP_CUDA_CHECK=1   \
deepspeed   --include "localhost:0" --master_port 29500  /home/yuhaiyang/zyl/code/LatentDoc/latentdoc/train/train_sam_opt_1024_with_ae_recon.py   \
            --deepspeed /home/yuhaiyang/zyl/code/LatentDoc/zero_config/zero0.json \
            --model_type  sam_opt_1024_with_ae_with_projector_down4_recon  \
            --model_name_or_path   /home/yuhaiyang/zyl/code/LatentDoc/pretrained_weight/models--facebook--opt-125m               \
            --vision_encoder    /home/yuhaiyang/zyl/code/LatentDoc/pretrained_weight/sam_vit_b_01ec64.pth \
            --ae /home/yuhaiyang/zyl/code/LatentDoc/pretrained_weight/ae_bestmodel.pth   \
            --with_ae_loss True  \
            --ae_loss_weight 11 \
            --img_size 1024    \
            --img_token_len 64 \
            --freeze_vision_encoder False    \
            --freeze_lm_model False      \
            --freeze_ae False  \
            --is_ae_eval False \
            --resume False \
            --bf16 True                \
            --per_device_eval_batch_size 1  \
            --gradient_accumulation_steps 1     \
            --evaluation_strategy "no"    \
            --save_strategy "steps"    \
            --save_steps 2   \
            --save_total_limit 10   \
            --weight_decay 0.05    \
            --warmup_ratio 0.15   \
            --lr_scheduler_type 'cosine_with_restarts' \
            --logging_steps 1 --tf32 True   \
            --model_max_length 2048    \
            --gradient_checkpointing True     \
            --dataloader_num_workers 12      \
            --report_to none       \
            --per_device_train_batch_size 2  \
            --num_train_epochs 500000         \
            --learning_rate 5e-5        \
            --datasets  test    \
            --output_dir /home/yuhaiyang/zyl/code/LatentDoc/exps/recon_test_4    \