DS_SKIP_CUDA_CHECK=1   \
deepspeed   --include "localhost:0,1,2,3,4,5,6,7" --master_port 29500  /home/fdu02/fdu02_dir/lw/code/LatentDoc/latentdoc/train/train_sam_opt_1024_with_ae_recon.py  \
            --deepspeed /home/fdu02/fdu02_dir/lw/code/LatentDoc/zero_config/zero0.json \
            --model_type  sam_opt_1024_with_ae_with_projector_down4_recon  \
            --model_name_or_path   /home/fdu02/fdu02_dir/lw/pretrained_weight/models--facebook--opt-125m               \
            --vision_encoder    /home/fdu02/fdu02_dir/lw/pretrained_weight/sam_vit/sam_vit_b_01ec64.pth \
            --ae /home/fdu02/fdu02_dir/lw/pretrained_weight/ae_bestmodel.pth   \
            --with_ae_loss True  \
            --ae_loss_weight 10 \
            --img_size 1024    \
            --img_token_len 64 \
            --freeze_vision_encoder False    \
            --freeze_lm_model False      \
            --freeze_ae False  \
            --is_ae_eval False \
            --resume False \
            --bf16 True                \
            --per_device_eval_batch_size 1  \
            --gradient_accumulation_steps 1     \
            --evaluation_strategy "no"    \
            --save_strategy "steps"    \
            --save_steps 500   \
            --save_total_limit 100   \
            --weight_decay 0.05    \
            --warmup_ratio 0.15   \
            --lr_scheduler_type 'cosine_with_restarts' \
            --logging_steps 1 --tf32 True   \
            --model_max_length 2048    \
            --gradient_checkpointing True     \
            --dataloader_num_workers 12      \
            --report_to none       \
            --per_device_train_batch_size 6  \
            --num_train_epochs 50         \
            --learning_rate 5e-5        \
            --datasets  pdf_cn_30k+pdf_en_30k    \
            --output_dir /home/fdu02/fdu02_dir/zyl/exp/"(8-14)input_1024_token_num_64_recon_first"    \