deepspeed   --include "localhost:1" --master_port 29501 /home/yuhaiyang/zlw/LatentDoc/latentdoc/train/train_resnet_opt_512.py   \
            --deepspeed /home/yuhaiyang/zlw/LatentDoc/zero_config/zero0.json \
            --model_name_or_path /home/yuhaiyang/zlw/pretrained_weight/models--facebook--opt-125m                           \
            --vision_encoder /home/yuhaiyang/zlw/pretrained_weight/Resnet/resnet152-394f9c45.pth \
            --img_size 512   \
            --freeze_vision_encoder False    \
            --freeze_lm_model False      \
            --bf16 True                \
            --per_device_eval_batch_size 16  \
            --gradient_accumulation_steps 1     \
            --evaluation_strategy "no"    \
            --save_strategy "steps"    \
            --save_steps 500    \
            --save_total_limit 1   \
            --weight_decay 0.    \
            --warmup_ratio 0.03   \
            --lr_scheduler_type 'cosine_with_restarts' \
            --logging_steps 1 --tf32 True   \
            --model_max_length 2048    \
            --gradient_checkpointing True     \
            --dataloader_num_workers 8      \
            --report_to none       \
            --per_device_train_batch_size 3  \
            --num_train_epochs 2         \
            --learning_rate 5e-5        \
            --datasets  zhongtie_doc    \
            --output_dir /home/yuhaiyang/zlw/LatentDoc/exps/resnet_deepspeed_cosine_with_restarts_self    \