deepspeed   --include "localhost:2" --master_port 29500 /home/yuhaiyang/zlw/LatentDoc/latentdoc/train/train_sam_opt_1024.py   \
            --deepspeed /home/yuhaiyang/zlw/Vary-toy-main/Vary-master/zero_config/zero2.json \
            --model_name_or_path /home/yuhaiyang/zlw/pretrained_weight/models--facebook--opt-125m                           \
            --vision_encoder /home/yuhaiyang/zlw/pretrained_weight/sam_vit_b_01ec64.pth \
            --img_size 1024   \
            --freeze_vision_encoder True    \
            --freeze_lm_model False      \
            --bf16 True                \
            --per_device_eval_batch_size 16  \
            --gradient_accumulation_steps 1     \
            --evaluation_strategy "no"    \
            --save_strategy "steps"    \
            --save_steps 500    \
            --save_total_limit 1   \
            --weight_decay 0.    \
            --warmup_ratio 0.03   \
            --lr_scheduler_type 'cosine_with_restarts' \
            --logging_steps 1 --tf32 True   \
            --model_max_length 2048    \
            --gradient_checkpointing True     \
            --dataloader_num_workers 8      \
            --report_to none       \
            --per_device_train_batch_size 4   \
            --num_train_epochs 2         \
            --learning_rate 5e-3        \
            --datasets  zhongtie_doc    \
            --output_dir /home/yuhaiyang/zlw/LatentDoc/exps/sam_deepspeed_cosine_with_restarts_self    \